### PR TITLE
add Cal-QL

### PR DESCRIPTION
**Pull request by jlidard**
This change is [Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/6)

### CODE REVIEW

**Review by allenzren — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/6)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @jlidard)

___
*[`agent/dataset/sequence.py` line 199 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7ue5Bw7wQuHg5p3w9R:-O7ue5Bx3kiu3WvJYwdZ:b9l21lx) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/agent/dataset/sequence.py#L199)):*
> ```Python
>         for i, traj_length in enumerate(cumulative_traj_length):
>             returns = torch.cumsum(self.rewards[prev_traj_length:traj_length], dim=0)
>             self.reward_to_go[prev_traj_length : traj_length - 1] = torch.flip(
> ```

Cal-QL uses discounted cumulative rewards https://github.com/nakamotoo/Cal-QL/blob/ac6eafec22e8d60836573e1f488c7f626ce8a77e/JaxCQL/replay_buffer.py#L293
___
*[`agent/finetune/train_calql_agent.py` line 214 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7ug54KATfFeqDrgSER:-O7ug54KATfFeqDrgSES:bqch6o6) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/agent/finetune/train_calql_agent.py#L214)):*
> ```Python
>             cumulative_traj_length = np.cumsum(traj_lengths)
>             prev_traj_length = 0
>             for i, traj_length in enumerate(cumulative_traj_length):
> ```

discount again
___
*[`model/rl/gaussian_calql.py` line 38 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7uhqLx5cKb70SUfu_D:-O7uhqLx5cKb70SUfu_E:bypdet7) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/model/rl/gaussian_calql.py#L38)):*
> ```Python
> 
>         # initialize target networks
>         self.actor = actor.to(self.device)
> ```

why use actor instead of just network?
___
*[`model/rl/gaussian_calql.py` line 58 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7uj-wc6yYO4lJz2OT8:-O7uj-wc6yYO4lJz2OT9:blszec1) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/model/rl/gaussian_calql.py#L58)):*
> ```Python
>         q_data1, q_data2 = self.critic(obs, actions)
>         with torch.no_grad():
>             next_actions, next_log_probs = self.forward(
> ```

Looks like Cal-QL uses multiple samples by default https://github.com/nakamotoo/Cal-QL/blob/ac6eafec22e8d60836573e1f488c7f626ce8a77e/JaxCQL/conservative_sac.py#L177, i.e., `cql_max_target_backup=True` by default
___
*[`model/rl/gaussian_calql.py` line 63 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7uiD5j0XNdqRUcDWQs:-O7uiD5j0XNdqRUcDWQt:b27c1cu) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/model/rl/gaussian_calql.py#L63)):*
> ```Python
>             next_q1, next_q2 = self.target_critic(next_obs, next_actions)
>             target_q1 = rewards + gamma * (1 - dones) * next_q1
>             target_q2 = rewards + gamma * (1 - dones) * next_q2
> ```

need to backup entropy with alpha https://github.com/nakamotoo/Cal-QL/blob/ac6eafec22e8d60836573e1f488c7f626ce8a77e/JaxCQL/conservative_sac.py#L197
___
*[`model/rl/gaussian_calql.py` line 128 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7uiWV9608_5M9p_h9M:-O7uiWV9608_5M9p_h9N:bswoo1k) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/model/rl/gaussian_calql.py#L128)):*
> ```Python
>         return actor_loss
> 
>     # todo: remove
> ```

I think we need this. Cal-QL does automatic temperature tuning by default https://github.com/nakamotoo/Cal-QL/blob/ac6eafec22e8d60836573e1f488c7f626ce8a77e/JaxCQL/conservative_sac.py#L27
___
*[`model/rl/gaussian_calql.py` line 148 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7uhxDn3ul-XLmHTu6p:-O7uhxDn3ul-XLmHTu6q:bpp6stj) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/model/rl/gaussian_calql.py#L148)):*
> ```Python
>     # ---------- Sampling ----------#
> 
>     def forward(
> ```

not needed

**Review by jlidard — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/6)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @allenzren)

___
*[`agent/dataset/sequence.py` line 199 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7ue5Bw7wQuHg5p3w9R:-O7uy8FFBP7gwXs2Lu2o:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/agent/dataset/sequence.py#L199)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

Cal-QL uses discounted cumulative rewards https://github.com/nakamotoo/Cal-QL/blob/ac6eafec22e8d60836573e1f488c7f626ce8a77e/JaxCQL/replay_buffer.py#L293
</blockquote></details>

Done.
___
*[`agent/finetune/train_calql_agent.py` line 214 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7ug54KATfFeqDrgSER:-O7uy93pDkCf7JvLa4MG:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/agent/finetune/train_calql_agent.py#L214)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

discount again
</blockquote></details>

Done.
___
*[`model/rl/gaussian_calql.py` line 38 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7uhqLx5cKb70SUfu_D:-O7uyACrDVxON2K_Ctjn:b-a7erap) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/model/rl/gaussian_calql.py#L38)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

why use actor instead of just network?
</blockquote></details>

We can remove in a later commit, but it is needed currently for backward compatibility (loading a pretrained model with self.actor)
___
*[`model/rl/gaussian_calql.py` line 58 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7uj-wc6yYO4lJz2OT8:-O7uyJW40U5gO7y0DRDA:b-j53mte) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/model/rl/gaussian_calql.py#L58)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

Looks like Cal-QL uses multiple samples by default https://github.com/nakamotoo/Cal-QL/blob/ac6eafec22e8d60836573e1f488c7f626ce8a77e/JaxCQL/conservative_sac.py#L177, i.e., `cql_max_target_backup=True` by default
</blockquote></details>

Done, currently I use a for loop, but we can add batched sampling if needed. However, it will be a pain because of the dictionary observation
___
*[`model/rl/gaussian_calql.py` line 63 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7uiD5j0XNdqRUcDWQs:-O7uyVnCAhz-1cC2Wm_k:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/model/rl/gaussian_calql.py#L63)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

need to backup entropy with alpha https://github.com/nakamotoo/Cal-QL/blob/ac6eafec22e8d60836573e1f488c7f626ce8a77e/JaxCQL/conservative_sac.py#L197
</blockquote></details>

Done.
___
*[`model/rl/gaussian_calql.py` line 128 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7uiWV9608_5M9p_h9M:-O7uyWcG7igZqysulEbB:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/model/rl/gaussian_calql.py#L128)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

I think we need this. Cal-QL does automatic temperature tuning by default https://github.com/nakamotoo/Cal-QL/blob/ac6eafec22e8d60836573e1f488c7f626ce8a77e/JaxCQL/conservative_sac.py#L27
</blockquote></details>

Done.
___
*[`model/rl/gaussian_calql.py` line 148 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7uhxDn3ul-XLmHTu6p:-O7uyYpK2KK-IlGmwsIC:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/model/rl/gaussian_calql.py#L148)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.

**Review by jlidard — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/6)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @allenzren)

___
*[`model/rl/gaussian_calql.py` line 38 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7uhqLx5cKb70SUfu_D:-O7v3Cq7DsmsHGqI2jtI:b-v6s1o3) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/model/rl/gaussian_calql.py#L38)):*
<details><summary><i>Previously, jlidard (Justin Lidard) wrote…</i></summary><blockquote>

We can remove in a later commit, but it is needed currently for backward compatibility (loading a pretrained model with self.actor)
</blockquote></details>

Removed. 
___
*[`model/rl/gaussian_calql.py` line 58 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7uj-wc6yYO4lJz2OT8:-O7v37qX9Lpp87r-dhNO:bjsl1rk) ([raw file](https://github.com/jlidard/dppo-dev/blob/13fcf7109c95705684bf5b4a5640ce5de3be1241/model/rl/gaussian_calql.py#L58)):*
<details><summary><i>Previously, jlidard (Justin Lidard) wrote…</i></summary><blockquote>

Done, currently I use a for loop, but we can add batched sampling if needed. However, it will be a pain because of the dictionary observation
</blockquote></details>

Actually changed to batched sampling here and then later on for the random actions

**Review by allenzren — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r3, 4 of 4 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/6)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @jlidard)

___
*[`agent/dataset/sequence.py` line 203 at r4](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7v7WITCXfeM5Z7jEVs:-O7v7WIU8e1CbbaiOHKL:b-l7qj2e) ([raw file](https://github.com/jlidard/dppo-dev/blob/75dc0462561a21a49833639e6bff25a8edda73e9/agent/dataset/sequence.py#L203)):*
> ```Python
>                 list(
>                     reversed(
>                         list(
> ```

You can do list(...)[::-1] instead of list(reversed(list(...)))
___
*[`agent/finetune/train_calql_agent.py` line 196 at r4](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7v7o2k0Iy8RClh46NY:-O7v7o2k0Iy8RClh46NZ:b7mb2cg) ([raw file](https://github.com/jlidard/dppo-dev/blob/75dc0462561a21a49833639e6bff25a8edda73e9/agent/finetune/train_calql_agent.py#L196)):*
> ```Python
>                         action_buffer.append(action_venv[i])
>                         reward_buffer.append(reward_venv[i] * self.scale_reward_factor)
>                         done_buffer.append(done_venv[i])
> ```

need to account for truncation. Check rlpd or ibrl agent
___
*[`agent/finetune/train_calql_agent.py` line 219 at r4](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7v7t5p0bIcEHCHkRfQ:-O7v7t5p0bIcEHCHkRfR:b-2guby3) ([raw file](https://github.com/jlidard/dppo-dev/blob/75dc0462561a21a49833639e6bff25a8edda73e9/agent/finetune/train_calql_agent.py#L219)):*
> ```Python
> 
>                 # Compute discounted returns using accumulate and reverse
>                 returns = list(
> ```

same here
___
*[`model/rl/gaussian_calql.py` line 39 at r4](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7v8FI7Ab6VKGr2Qx3e:-O7v8FI7Ab6VKGr2Qx3f:bgglzv6) ([raw file](https://github.com/jlidard/dppo-dev/blob/75dc0462561a21a49833639e6bff25a8edda73e9/model/rl/gaussian_calql.py#L39)):*
> ```Python
>         self.target_critic = deepcopy(critic).to(self.device)
> 
>         if actor_critic_path is not None:
> ```

remove this part too

**Review by jlidard — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/6)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @allenzren)

___
*[`agent/dataset/sequence.py` line 203 at r4](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7v7WITCXfeM5Z7jEVs:-O7vOyGW3p6YPf9S4zmH:bs7wumx) ([raw file](https://github.com/jlidard/dppo-dev/blob/75dc0462561a21a49833639e6bff25a8edda73e9/agent/dataset/sequence.py#L203)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

You can do list(...)[::-1] instead of list(reversed(list(...)))
</blockquote></details>

Done. 
___
*[`agent/finetune/train_calql_agent.py` line 196 at r4](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7v7o2k0Iy8RClh46NY:-O7vOypr4l57PBGb5ecP:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/75dc0462561a21a49833639e6bff25a8edda73e9/agent/finetune/train_calql_agent.py#L196)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

need to account for truncation. Check rlpd or ibrl agent
</blockquote></details>

Done.
___
*[`agent/finetune/train_calql_agent.py` line 219 at r4](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7v7t5p0bIcEHCHkRfQ:-O7vP29PD-EUB7w2pT1i:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/75dc0462561a21a49833639e6bff25a8edda73e9/agent/finetune/train_calql_agent.py#L219)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`model/rl/gaussian_calql.py` line 39 at r4](https://reviewable.io/reviews/jlidard/dppo-dev/6#-O7v8FI7Ab6VKGr2Qx3e:-O7vP2m00CHAydCOhE5h:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/75dc0462561a21a49833639e6bff25a8edda73e9/model/rl/gaussian_calql.py#L39)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

remove this part too
</blockquote></details>

Done.

**Review by allenzren — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jlidard)

**Pull request merged**
